name: Feature request ✨
title: "[FEATURE]: "
description: Suggest a new idea.
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Please provide a searchable summary of the issue in the title above ⬆️.

        Thanks for contributing by creating an issue! ❤️

  - type: textarea
    attributes:
      label: Summary 💡
      description: Describe how it should work.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Examples 🌈
      description: Provide a link to other implementations, or screenshots of the expected behavior.

  - type: textarea
    attributes:
      label: Motivation 🔦
      description: What are you trying to accomplish? How has the lack of this feature affected you? Providing context helps us come up with a solution that is more useful in the real world.